app:
  name: "my-project"
  version: "1.0.0"
  session:
    name: "csid"
    secret: "super-secret-123"

server:
  host: "0.0.0.0"
  port: 8000
  read_timeout: 10
  write_timeout: 10

logger:
  level: "debug"
  colors: true
  timestamp: true
